version: "3"
services:
  shadow_db:
    image: postgres:latest
    container_name: shadow_db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - shadow_db:/var/lib/postgresql/data

  fcs:
    build: .
    container_name: fcs
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://shadow_db:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run dev"
    depends_on:
      - shadow_db

volumes:
  shadow_db:
