version: "3"
services:
  fcs_db_test:
    image: postgres:latest
    container_name: fcs_db_test
    env_file:
      - .env.test

  fcs:
    build: .
    container_name: fcs
    env_file:
      - .env.test
    entrypoint: dockerize -wait tcp://fcs_db_test:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run dev"
    depends_on:
      - fcs_db_test
